Repository iRNA-COSI/APAeval, pull requests merged in 2022-10, with the labels that each got.

#393 Execution workflow: IsoSCM - report Format 04 BED file in workflow (per-PAS fractional relative usage)
  execution_workflows/IsoSCM/README.md
  execution_workflows/IsoSCM/bin/check_input_params.py
  execution_workflows/IsoSCM/bin/postprocess.py
  execution_workflows/IsoSCM/conf/modules.config
  execution_workflows/IsoSCM/modules/check_input_params.nf
  execution_workflows/IsoSCM/modules/postprocess_relative_usage_quantification.nf
  execution_workflows/IsoSCM/modules/star_alignment.nf
  execution_workflows/IsoSCM/subworkflows/input_check.nf
  execution_workflows/IsoSCM/subworkflows/run_isoscm.nf
Labels: ready for review

#423 Getutr nextflow
  execution_workflows/GETUTR/Dockerfile
  execution_workflows/GETUTR/README.md
  execution_workflows/GETUTR/bin/check_samplesheet.py
  execution_workflows/GETUTR/conf/base.config
  execution_workflows/GETUTR/conf/modules.config
  execution_workflows/GETUTR/main.nf
  execution_workflows/GETUTR/modules/check_samplesheet.nf
  execution_workflows/GETUTR/modules/functions.nf
  execution_workflows/GETUTR/modules/getutr_process.nf
  execution_workflows/GETUTR/modules/postprocessing_identification.nf
  execution_workflows/GETUTR/nextflow.config
  execution_workflows/GETUTR/samplesheet.csv
  execution_workflows/GETUTR/subworkflows/input_check.nf
  execution_workflows/GETUTR/subworkflows/run_getutr.nf
  execution_workflows/GETUTR/workflow/execute_getutr.nf
Labels: reviews to address

#444 SWF: allow multiple challenges per infile
  summary_workflows/JSON_templates/src/JSON_templates/main.py
  summary_workflows/README.md
  summary_workflows/identification/APAeval_I_test_data/ref/challenge_2.TE.mm10.bed
  summary_workflows/identification/README.md
  summary_workflows/identification/identification_dockers/i_metrics/compute_metrics.py
  summary_workflows/identification/identification_dockers/i_validation/validation.py
  summary_workflows/identification/specification/I_benchmark_specification.md
  summary_workflows/identification/tool_event.config
  summary_workflows/quantification/APAeval_Q_test_data/ref/challenge_2.TE.mm10.bed
  summary_workflows/quantification/README.md
  summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
  summary_workflows/quantification/quantification_dockers/q_validation/validation.py
  summary_workflows/quantification/specification/Q_benchmark_specification.md
  summary_workflows/quantification/tool_event.config
Labels: enhancement, high priority
