Repository iRNA-COSI/APAeval, pull requests merged in 2022-08, with the labels that each got.

#396 [Bug fix] Dapars: Skip 'chr' prefix check for non main chromosomes
  execution_workflows/DaPars/bin/check_bedgraph.py
Labels: bug

#398 [Bug fix] Dapars: fix config file creation for relative usage quantification run mode
  execution_workflows/DaPars/bin/create_config_file.py
Labels: bug, ready for review

#405 SWF: modules for code deduplication
  summary_workflows/JSON_templates/README.md
  summary_workflows/JSON_templates/pyproject.toml
  summary_workflows/JSON_templates/requirements.txt
  summary_workflows/JSON_templates/setup.cfg
  summary_workflows/JSON_templates/setup.py
  summary_workflows/JSON_templates/src/JSON_templates/Benchmarking_minimal_datasets_schema.json
  summary_workflows/JSON_templates/src/JSON_templates/__init__.py
  summary_workflows/JSON_templates/src/JSON_templates/main.py
  summary_workflows/quantification/quantification_dockers/q_metrics/Dockerfile
  summary_workflows/quantification/quantification_dockers/q_metrics/JSON_templates/__init__.py
  summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py
  summary_workflows/quantification/quantification_dockers/q_metrics/requirements.txt
  summary_workflows/quantification/quantification_dockers/q_validation/Dockerfile
  summary_workflows/quantification/quantification_dockers/q_validation/JSON_templates/Benchmarking_minimal_datasets_schema.json
  summary_workflows/quantification/quantification_dockers/q_validation/JSON_templates/JSON_templates.py
  summary_workflows/quantification/quantification_dockers/q_validation/JSON_templates/__init__.py
  summary_workflows/quantification/quantification_dockers/q_validation/requirements.txt
  summary_workflows/quantification/quantification_dockers/q_validation/validation.py
  utils/matchPAS/README.md
  utils/matchPAS/pyproject.toml
  utils/matchPAS/requirements.txt
  utils/matchPAS/setup.cfg
  utils/matchPAS/setup.py
  utils/matchPAS/src/matchPAS/__init__.py
  utils/matchPAS/src/matchPAS/main.py
Labels: enhancement, ready for review

#403 [Bug Fix] APAtrap cast output to string before parsing and avoid time out error
  execution_workflows/APAtrap/README.md
  execution_workflows/APAtrap/bin/convert_to_bed.py
  execution_workflows/APAtrap/conf/base.config
  execution_workflows/APAtrap/modules/de_apa.nf
  execution_workflows/APAtrap/modules/identify_distal_3utr.nf
  execution_workflows/APAtrap/modules/predict_apa.nf
Labels: ready for review
